Add service to doctor
Web-Rangers/Asclepius-Client pull request #51
Opened 2022-09-20 10:24 UTC by IrinaEndeladze

2022-09-20 10:27 UTC, NikitoriusMinsk requested changes

2022-09-20 10:27 UTC, NikitoriusMinsk commented on components/tabs/AboutDoctorTab.tsx
> +	useEffect(() => {}, [doctor]);
remove empty useEffect

2022-09-20 10:27 UTC, NikitoriusMinsk commented
Check merge conficts

2022-09-27 07:32 UTC, NikitoriusMinsk requested changes

2022-09-27 07:32 UTC, NikitoriusMinsk commented on pages/doctors/doctors_detailed/index.tsx
> +		[id, 'FrelnacerAndClinicDoctors'],
change id to doctor_id to avoid conflicting cache keys

2022-09-27 07:44 UTC, IrinaEndeladze commented on pages/doctors/doctors_detailed/index.tsx
> +		[id, 'FrelnacerAndClinicDoctors'],
this  id which i use, is doctor's id? you mean to write like this  "doctor_id" ?

2022-09-27 07:48 UTC, NikitoriusMinsk commented on pages/doctors/doctors_detailed/index.tsx
> +		[id, 'FrelnacerAndClinicDoctors'],
`doctor_${id}`

2022-09-30 08:12 UTC, merged